name: Laravel CI

on:
  pull_request:
    paths:
      - "laravel/**"
      - ".github/workflows/laravel.yml"

jobs:
  Laravel:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        php: [8.3]

    timeout-minutes: 15

    defaults:
      run:
        working-directory: laravel

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test_db
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_ENV: testing
      APP_URL: http://localhost

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Dump autoload
        run: composer dump-autoload

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Lint (PHP_CodeSniffer)
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 app routes tests

      - name: Copy .env file and generate app key
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run tests
        run: vendor/bin/phpunit
